# Generated by Django 3.1.4 on 2020-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('blog_slug', models.CharField(max_length=100)),
                ('blog_author', models.CharField(max_length=50)),
                ('blog_time', models.TimeField(blank=True)),
            ],
        ),
    ]
