# Generated by Django 3.1.4 on 2020-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201220_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_thumbnail',
            field=models.ImageField(default='', upload_to='images/blog-post/'),
            preserve_default=False,
        ),
    ]
