# Generated by Django 3.1.4 on 2020-12-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_date',
            new_name='contact_time',
        ),
    ]
